INSERT INTO country (name) VALUES ('India');
INSERT INTO country (name) VALUES ('Brazil');
INSERT INTO country (name) VALUES ('USA');
INSERT INTO country (name) VALUES ('Italy');
INSERT INTO country (name) VALUES ('Portugal');
INSERT INTO country (name) VALUES ('UK');
INSERT INTO country (name) VALUES ('Japan');
INSERT INTO country (name) VALUES ('South Korea');
INSERT INTO country (name) VALUES ('China');
INSERT INTO country (name) VALUES ('Russia');
INSERT INTO country (name) VALUES ('Mexico');
INSERT INTO country (name) VALUES ('Argentina');
INSERT INTO country (name) VALUES ('South Africa');
INSERT INTO country (name) VALUES ('Egypt');
INSERT INTO country (name) VALUES ('Canada');
INSERT INTO country (name) VALUES ('Australia');
INSERT INTO country (name) VALUES ('Germany');
INSERT INTO country (name) VALUES ('France');
INSERT INTO country (name) VALUES ('Spain');
